### ISSUE TITLE
SeqVec example doesn't work

### ISSUE THREAD

**Issue by brechtmann** [kipoi/models#206]
It fails with the following error:

```
kipoi predict SeqVec/embedding   --dataloader_args='{"fasta_file": "example/fasta_file"}'   -o '/tmp/SeqVec|embedding.example_pred.tsv'
Traceback (most recent call last):
  File "/opt/modules/i12g/anaconda/envs/kipoi-SeqVec__embedding/bin/kipoi", line 8, in <module>
    sys.exit(main())
  File "/opt/modules/i12g/anaconda/envs/kipoi-SeqVec__embedding/lib/python3.6/site-packages/kipoi/__main__.py", line 105, in main
    command_fn(args.command, sys.argv[2:])
  File "/opt/modules/i12g/anaconda/envs/kipoi-SeqVec__embedding/lib/python3.6/site-packages/kipoi/cli/main.py", line 211, in cli_predict
    dataloader_kwargs = parse_json_file_str_or_arglist(args.dataloader_args, parser)
  File "/opt/modules/i12g/anaconda/envs/kipoi-SeqVec__embedding/lib/python3.6/site-packages/kipoi_utils/utils.py", line 305, in parse_json_file_str_or_arglist
    return parse_json_file_str(dataloader_args[0])
  File "/opt/modules/i12g/anaconda/envs/kipoi-SeqVec__embedding/lib/python3.6/site-packages/kipoi_utils/utils.py", line 275, in parse_json_file_str
    return yaml.load(extractor_args, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'
```

**Comment by Hoeze** [comment]
@mheinzinger would you mind looking into this issue?
I think it has something to do with the PyYAML version that is used in your environment.

**Comment by KalinNonchev** [comment]
Hi,
I checked this problem and it is caused because of [allennlp](https://pypi.org/project/allennlp/).  The [current version](https://anaconda.org/conda-forge/allennlp) of allennlp which conda supports is 0.7.2. This version downgrades PyYAML from 5.3.1 to 3.13. 
I installed allennlp 0.9.0(last version) via pip. It works with PyYAML 5.3.1. I opened [here](https://github.com/conda-forge/allennlp-feedstock/issues/9) an issue if allennlp 0.9.0 can be also available.
I found the same [issue](https://github.com/conda-forge/allennlp-feedstock/issues/2) about allennlp 0.8.0 from last year, which is still not available on conda, so 0.9.0 will probably not be available soon.
